### ISSUE TITLE
Request - Release

### ISSUE THREAD

**Issue by spreedated** [angelinn/Mosquitto-Auth-Plugin-Windows#1]
Hi there, first of all thanks for the port.
Could you please provide a "release" of the built *.dll for download?

**Comment by angelinn** [comment]
Attached a release. 
Please let me know if you use it and the release runs well. 

I can't build it right now, so I found old build in my source folders, which should work.
Remember to add the required openssl, curl and pthread dlls to the executing folder.

**Comment by captainerd** [comment]
The DLL you uploaded seems to be a 32bit DLL while i had installed mosquito 64bit and wasn't working,

**Comment by captainerd** [comment]
I re-comment just to confirm it works with mosquitto 32bit exe.

Using these dlls of curl, openssl from your own repo at: Mosquitto-Auth-Plugin-Windows/tree/master/src/auth%20plugin/deps

And using the release dll auth-plugin.dll. All in the root directory of mosquito at program files (replacing blindly some pre-existing dlls)

Because it didn't wanted to load to a different subdir. However, it works. even tho I already finished build openssl for 64bit and curl for 64bit.
